FROM ubuntu:xenial

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=cpuminerscoin/cpuminerscoin
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo
#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY cpuminerscoin.tar.gz /cpuminerscoin.tar.gz
RUN tar -xvf /cpuminerscoin.tar.gz

#xenial
#Missing requirement: libtool
RUN apt install -yqq libtool-bin
RUN cd /cpuminerscoin/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /cpuminerscoin && scripts/windows-crosscompile/compile-cpuminerscoin.sh
