FROM debian:jessie

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=cpuminerscoin/cpuminerscoin
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
	git \
	sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1 

COPY cpuminerscoin.tar.gz /cpuminerscoin.tar.gz
RUN tar -xvf /cpuminerscoin.tar.gz

RUN cd /cpuminerscoin && ./scripts/dependencies-ubuntu.sh && ./scripts/install-ubuntu.sh && \
	apt-get purge git build-essential -qy && \
	apt-get autoremove -qy && \
	apt-get clean
